# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ccb2c65c77570ba1175107142c7f211d454cd94179da49f9d1b05d8f0dd908db633e55bd613f259cae7669b5334e19fd42130eae14393792f67e464a841daf4

test:
  secret_key_base: 5345833f44c8b0032557f1e20bef582a7958a4295966afbdc9fd35f597d18c433dc86f0a77b434be31d23de3994a68297b589eb94c5749ca1930c9aa0b233abe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
